In [1]:
import pandas as pd

In [3]:
Df=pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")

# 1. Adding a new column

# 1.1 assign()

   when to use assign?
      

*   Add multiple coulmns in a single line of code
*   When you need to overwrite the values of an existing coulmns(best practice).

It returns a new object(a copy) with all the original columns in addition to the new ones

In [4]:
import numpy as np

In [5]:
# create random numbers for our new score columns
score1 = np.random.randint(1,101,size = 3964)
score2 = np.random.randint(1,101,size=3964)

In [6]:
# create a series using the random numbers
series1 = pd.Series(score1,index=np.arange(0,3964))
series2 = pd.Series(score2,index=np.arange(0,3964))

In [7]:
# using assign() to add multiple columns
Df.assign(score1=series1,score2=series2)

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,score1,score2
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,11,31
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,23,84
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,83,56
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,75,41
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,45,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,77,8
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,55,42
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,53,35
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,77,52
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,11,75

In [8]:
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

In [10]:
# here the values are not updated basically it creates out a new object and provides the new object hence we need to overwrite the existing one
df = Df.assign(score1=series1,score2=series2)
df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,score1,score2
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,11,31
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,23,84
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,83,56
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,75,41
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,45,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,77,8
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,55,42
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,53,35
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,77,52
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,11,75

# 1.2 insert()

   Inserts a new column at a specific position or index.It directly updates the date in the dataframe no copy produced.

In [11]:
# using index() to add a column at a specific position
Df.insert(1,"test",series1)
Df

,Global Rank,test,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,11,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+
1,2,23,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+
2,3,83,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+
3,4,75,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+
4,5,45,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,77,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,55,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,53,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,77,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,11,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M