In [2]:
import pandas as pd

In [4]:
# reaading the csv file
df = pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")
df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

# 1 Math Operations
# 1.1 Operations in columns

In [5]:
# select a column and calculate total sum
df["Views (B)"].sum()

np.float64(4836.412)

In [10]:
# count, mean, std, max and min
df["Views (B)"].mean()
df["Views (B)"].count()
df["Views (B)"].std()
df["Views (B)"].max()
df["Views (B)"].min()

0.0

In [12]:
# easier calculation with .describe()
df.describe()

,Global Rank,Subscribers,Total Views,Total Videos,Views per Subscriber,Views per Video,Subscribers (M),Views (B)
count,3964.000000,3.964000e+03,3.964000e+03,3964.000000,3.962000e+03,3.963000e+03,3964.000000,3964.000000
mean,1982.500000,2.258728e+06,1.220083e+09,2121.621594,5.689710e+04,1.462053e+06,2.258671,1.220084
std,1144.452562,1.192432e+07,7.981924e+09,14379.953625,3.212099e+06,8.491853e+06,11.924335,7.981923
min,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,991.750000,6.507500e+04,2.591287e+07,139.750000,2.235525e+02,7.039800e+04,0.067500,0.026000
50%,1982.500000,3.430000e+05,1.353160e+08,610.500000,3.888800e+02,2.172010e+05,0.340000,0.135000
75%,2973.250000,1.330000e+06,5.888938e+08,1843.500000,7.352575e+02,6.970525e+05,1.330000,0.589000
max,3964.000000,4.740000e+08,3.356510e+11,541883.000000,2.021232e+08,2.320543e+08,474.000000,335.651000

1.2 Operations in rows

In [13]:
# calculating the sum in a row
df['Total Videos']+df['Total Views']+df['Views per Subscriber']

0       1.160060e+11
1       3.356510e+11
2       1.871862e+11
3       1.201140e+11
4       1.235460e+11
            ...
3959    2.914812e+06
3960    3.657866e+06
3961    4.046205e+08
3962             NaN
3963             NaN
Length: 3964, dtype: float64

In [15]:
# calculating the average score and assigning the result to a new column
df["average"] = (df['Total Videos']+df['Total Views']+df['Views per Subscriber'])/3
df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,average
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,3.866867e+10
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,1.118837e+11
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,6.239539e+10
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,4.003800e+10
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,4.118200e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,9.716039e+05
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,1.219289e+06
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,1.348735e+08
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,NaN
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,NaN