In [1]:
import pandas as pd

In [2]:
# reading the csv file
Df = pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")

In [3]:
Df.head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.546,🔴 100M+

# 1.Adding a new column
# Adding a new column with a scalar value

In [5]:
# adding new column to dataframe
Df["likes per video"] = 1000
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,likes per video
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,1000
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,1000
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,1000
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,1000
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,1000
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,1000
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,1000
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,1000
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,1000

# 1.2 Adding a new column with an array
The dataframe has 1000 rows, so we need to create an array with 1000 elements.

In [6]:
# import numpy
import numpy as np

In [14]:
# create an array of 1000 elements
language_score = np.arange(0,3964)

In [8]:
# To ensure this use length function
len(np.arange(0,1000))

1000

In [16]:
# adding a new column to dataframe with an array
Df["Language score"] = language_score
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,likes per video,Language score
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,1000,0
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,1000,1
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,1000,2
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,1000,3
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,1000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,1000,3959
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,1000,3960
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,1000,3961
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,1000,3962
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,1000,3963

In [19]:
# create random integer numbers between 1 and 100
lang_score = np.random.randint(1,100,size=3964)

In [18]:
# lenght test
len(np.random.randint(1,100,size=3964))
# here the minimum value is inclusive and max value is exclusive.

3964

In [21]:
Df["language score"] =  lang_score
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier,likes per video,Language score,language score
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+,1000,0,41
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+,1000,1,44
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+,1000,2,35
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+,1000,3,69
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+,1000,4,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M,1000,3959,67
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M,1000,3960,71
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M,1000,3961,46
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M,1000,3962,43
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M,1000,3963,14

In [24]:
# min alue inclusive and hig value exclusive
min(lang_score)
max(lang_score)

np.int64(99)

In [25]:
# create random float numbers between 1 and 100
np.random.uniform(1,100,size=3964)

array([49.42460091,  5.78790862, 75.46625548, ..., 46.66164824,
       50.65309729,  7.34743003])