In [1]:
import pandas as pd

In [9]:
Df = pd.read_csv("/content/youtube_4k_channels_cleaned.csv")
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

In [6]:
# show first 5 rows in a dataframe
Df.head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.546,🔴 100M+

In [8]:
#show last 5 rows in a dataframe
Df.tail()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2331839.0,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2438575.0,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,202123178.0,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,42060.0,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,326892269.0,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

In [11]:
#show last n rows in a dataframe
Df.head(10)

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.546,🔴 100M+
5,6,UCFFbwnve3yF62-tVXkTyHqg,Zee Music Company,122000000,8.696823e+10,15963,IN,Zee Music Company is part of India's leading t...,712.85,5448113.0,122.0,86.968,🔴 100M+
6,7,UCJ5v_MCY6GNUBTO8-D3XoAg,WWE,112000000,1.029290e+11,92131,Unknown,WWE on YouTube is your number one spot to catc...,919.01,1117201.0,112.0,102.929,🔴 100M+
7,8,UC-lHJZR3Gqxm24_Vd_AJ5Yw,PewDiePie,110000000,2.948522e+10,4660,JP,I make videos.,268.05,6327300.0,110.0,29.485,🔴 100M+
8,9,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,100000000,4.175643e+10,666,KR,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,417.56,62697348.0,100.0,41.756,🔴 100M+
9,10,UCLkAepWjdylmXSltofFvsYQ,BANGTANTV,83300000,2.717666e+10,2984,Unknown,This is the official YouTube channel of BTS. 방...,326.25,9107458.0,83.3,27.177,🟠 50–100M

In [13]:
# show first n rows in a dataframe
Df.tail(10)

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
3954,3955,UCKk0HhH1MxdvtlErWBWIELg,TarnAIThai - Topic,5,15224.0,48,Unknown,NaN,3.044800e+03,317.0,0.0,0.000,🔵 <1M
3955,3956,UC60z0OBnOjkDFJJEJ0VUywQ,Release - Topic,5,18364.0,1,Unknown,NaN,3.672800e+03,18364.0,0.0,0.000,🔵 <1M
3956,3957,UCcIHdFDHz6LjAb_sMp_axFQ,ARMONİ - Topic,5,13613.0,43,Unknown,NaN,2.722600e+03,317.0,0.0,0.000,🔵 <1M
3957,3958,UCEH_rDVTdmzzHIVHu_83umA,ilostmyfeelings - Topic,4,49776.0,16,Unknown,NaN,1.244400e+04,3111.0,0.0,0.000,🔵 <1M
3958,3959,UCMnIvt22T-bGvYalgYsKTtA,Furkan Kalkan - Topic,4,588138.0,18,Unknown,🎸 Furkan Kalkan – Psychedelic Anatolian Rock &...,1.470345e+05,32674.0,0.0,0.001,🔵 <1M
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2331839.0,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2438575.0,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,202123178.0,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,42060.0,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,326892269.0,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

In [14]:
# getting access to the shape attribute
Df.shape

(3964, 13)

In [16]:
#display n rows
pd.set_option("display.max_rows",3964)
Df

Output hidden; open in https://colab.research.google.com to view.

# 1 *Attributes*

In [17]:
# getting access to the shape attribute
Df.shape

(3964, 13)

In [18]:
#getting access to the index attribute
Df.index

RangeIndex(start=0, stop=3964, step=1)

In [19]:
#getting access to the column attribute
Df.columns

Index(['Global Rank', 'Channel ID', 'Channel Name', 'Subscribers',
       'Total Views', 'Total Videos', 'Country', 'Description',
       'Views per Subscriber', 'Views per Video', 'Subscribers (M)',
       'Views (B)', 'Tier'],
      dtype='object')

In [20]:
# data type of each column
Df.dtypes

Global Rank               int64
Channel ID               object
Channel Name             object
Subscribers               int64
Total Views             float64
Total Videos              int64
Country                  object
Description              object
Views per Subscriber    float64
Views per Video         float64
Subscribers (M)         float64
Views (B)               float64
Tier                     object
dtype: object

Object is always any kind of string.

# 2 Methods

In [21]:
# To show first 5 rows
Df.head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.546,🔴 100M+

In [22]:
# Showing the info of the dataframe
Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3964 entries, 0 to 3963
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Global Rank           3964 non-null   int64
 1   Channel ID            3964 non-null   object
 2   Channel Name          3964 non-null   object
 3   Subscribers           3964 non-null   int64
 4   Total Views           3964 non-null   float64
 5   Total Videos          3964 non-null   int64
 6   Country               3964 non-null   object
 7   Description           3457 non-null   object
 8   Views per Subscriber  3962 non-null   float64
 9   Views per Video       3963 non-null   float64
 10  Subscribers (M)       3964 non-null   float64
 11  Views (B)             3964 non-null   float64
 12  Tier                  3964 non-null   object
dtypes: float64(5), int64(3), object(5)
memory usage: 402.7+ KB

In [23]:
# describing basic statistics of the dataframe
Df.describe()

,Global Rank,Subscribers,Total Views,Total Videos,Views per Subscriber,Views per Video,Subscribers (M),Views (B)
count,3964.000000,3.964000e+03,3.964000e+03,3964.000000,3.962000e+03,3.963000e+03,3964.000000,3964.000000
mean,1982.500000,2.258728e+06,1.220083e+09,2121.621594,5.689710e+04,1.462053e+06,2.258671,1.220084
std,1144.452562,1.192432e+07,7.981924e+09,14379.953625,3.212099e+06,8.491853e+06,11.924335,7.981923
min,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,991.750000,6.507500e+04,2.591287e+07,139.750000,2.235525e+02,7.039800e+04,0.067500,0.026000
50%,1982.500000,3.430000e+05,1.353160e+08,610.500000,3.888800e+02,2.172010e+05,0.340000,0.135000
75%,2973.250000,1.330000e+06,5.888938e+08,1843.500000,7.352575e+02,6.970525e+05,1.330000,0.589000
max,3964.000000,4.740000e+08,3.356510e+11,541883.000000,2.021232e+08,2.320543e+08,474.000000,335.651000

# 3. Functions

In [24]:
# obtaining the length of the dataframe(number of rows)
len(Df)

3964

In [26]:
# Obtaining the highest index of the dataframe
max(Df.index)

3963

In [27]:
# Obatining the lowest index of the dataframe
min(Df.index)

0

In [28]:
# obtaining the data type
type(Df)

pandas.core.frame.DataFrame

In [30]:
# rounding the values of the datset
round(Df,2).head(5)

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.01,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.65,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.19,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.11,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.55,🔴 100M+