In [1]:
import pandas as pd

In [4]:
Df=pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")
Df

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,2.447400e+02,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India...",1.079260e+03,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...,9.956700e+02,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...,8.061300e+02,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,...",8.952600e+02,77751069.0,138.0,123.546,🔴 100M+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN,5.829598e+05,179372.0,0.0,0.002,🔵 <1M
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN,1.219288e+06,609644.0,0.0,0.002,🔵 <1M
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN,2.021232e+08,540.0,0.0,0.202,🔵 <1M
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN,NaN,42060.0,0.0,0.000,🔵 <1M
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN,NaN,603.0,0.0,0.327,🔵 <1M

# 1.Selecting one column
    1.1 Syntax 1

In [7]:
# select a column with [] (preferred way to select a column)
Df["Channel Name"]

0                             MrBeast
1                            T-Series
2                           SET India
3                       Vlad and Niki
4                   ✿ Kids Diana Show
                    ...
3959    Anatolian Arabesk Lab - Topic
3960         The Second Voice - Topic
3961                       Paramount+
3962                  Release - Topic
3963                       Paramount+
Name: Channel Name, Length: 3964, dtype: object

In [8]:
# check out the data type of a column
type(Df["Channel Name"])

pandas.core.series.Series

In [10]:
# series
Df["Channel Name"].index
Df["Channel Name"].head()

0              MrBeast
1             T-Series
2            SET India
3        Vlad and Niki
4    ✿ Kids Diana Show
Name: Channel Name, dtype: object

# 1.2 Syntax 2

In [14]:
# select a column with
Df.Country

0            US
1            IN
2            IN
3            US
4            US
         ...
3959    Unknown
3960    Unknown
3961    Unknown
3962    Unknown
3963    Unknown
Name: Country, Length: 3964, dtype: object

In [ ]:
# selext a column with . (pitfalls)
# Df.Channel Name
# It raises the error

In [16]:
# select the same column using []
Df["Channel Name"]

0                             MrBeast
1                            T-Series
2                           SET India
3                       Vlad and Niki
4                   ✿ Kids Diana Show
                    ...
3959    Anatolian Arabesk Lab - Topic
3960         The Second Voice - Topic
3961                       Paramount+
3962                  Release - Topic
3963                       Paramount+
Name: Channel Name, Length: 3964, dtype: object

# 1.Selecting two or more columns

In [17]:
# select 2 columns using [[]]
Df[["Channel Name","Country"]]

                       Channel Name  Country
0                           MrBeast       US
1                          T-Series       IN
2                         SET India       IN
3                     Vlad and Niki       US
4                 ✿ Kids Diana Show       US
...                             ...      ...
3959  Anatolian Arabesk Lab - Topic  Unknown
3960       The Second Voice - Topic  Unknown
3961                     Paramount+  Unknown
3962                Release - Topic  Unknown
3963                     Paramount+  Unknown

[3964 rows x 2 columns]

In [18]:
type(Df[["Channel Name","Country"]])

pandas.core.frame.DataFrame

In [19]:
# select 2 or more columns using [[]]
Df[["Global Rank","Channel ID",	"Channel Name",	"Subscribers",	"Total Views",	"Total Videos",	"Country",	"Description"]]

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,1.160060e+11,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,3.356510e+11,25757,IN,"Music can change the world"". T-Series is India..."
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,1.871860e+11,168366,IN,Sony Entertainment Television is one of the le...
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,1.201140e+11,1005,US,“Vlad & Niki” is the global preschool phenomen...
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,1.235460e+11,1589,US,"Welcome to Diana and Roma world - where Diana,..."
...,...,...,...,...,...,...,...,...
3959,3960,UCfp-vHLwJjuxcn47hBCfa0w,Anatolian Arabesk Lab - Topic,4,2.331839e+06,13,Unknown,NaN
3960,3961,UCQeiGH0k_gwOUpVfeQnRwkA,The Second Voice - Topic,2,2.438575e+06,4,Unknown,NaN
3961,3962,UCVieVPiy6vUHzV0fMoAS9ew,Paramount+,1,2.021232e+08,374138,Unknown,NaN
3962,3963,UCeAVhQQ4AkhtenvViPwLiXA,Release - Topic,0,4.206000e+04,1,Unknown,NaN
3963,3964,UC3nBSi6NwVKRLy29WfatJUw,Paramount+,0,3.268923e+08,541883,Unknown,NaN

In [23]:
# we can't select 2 or more columns with the "."
# Df.Country,Channel ID